### ISSUE TITLE
Fails to compile with GHC 7.10.3

### ISSUE THREAD

**Issue by Mikolaj** [Soostone/katip#104]
As you can see below, it fails with GHC 7.10.3:

https://matrix.hackage.haskell.org/#/package/katip/0.7.0.0/ghc-7.10.3@1542320680

**Comment by MichaelXavier** [comment]
The version tested in that package no longer claims to compile with GHC 7.10.3

https://hackage.haskell.org/package/katip-0.7.0.0/katip.cabal

**Comment by Mikolaj** [comment]
Too bad. Could you restrict the base bound so that an older version is picked for builds with GHC 7.10.3? Thank you.

**Comment by MichaelXavier** [comment]
There will be a lower bound in the next version of katip released.

**Comment by Mikolaj** [comment]
Thank you. In the mean time, I will CPP in the packages that depend on katip. Cheers!

**Comment by Mikolaj** [comment]
@MichaelXavier: Actually, I realized, the fix you committed won't work retroactively and 0.7.0.0 would still be a trap for installs. If that's not too much trouble, could you perhaps tweak the base bound also in the package meta-data at https://hackage.haskell.org/package/katip-0.7.0.0/katip.cabal/edit ? Then all is legit, safe and Hackage Matrix for your package and mine should be fixed as well.

**Comment by Mikolaj** [comment]
It works flawlessly now. Thank you.
