### ISSUE TITLE
update katip-elasticsearch

### ISSUE THREAD

**Issue by teto** [Soostone/katip#124]
```
src/Katip/Scribes/ElasticSearch/Internal.hs:41:1: error:
    Could not find module ‘Database.V5.Bloodhound’
    Perhaps you meant Database.Bloodhound (from bloodhound-0.17.0.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
41 | import qualified Database.V5.Bloodhound                  as V5
```
Note that 0.17 is unreleased, I use a fork for gh8.8 compatibility but the problem should be valid for the 0.16 release.

**Comment by MichaelXavier** [comment]
This is fixed in katip-elasticsearch-0.7.0.0

**Comment by teto** [comment]
yeah I saw afterwards it didn't even concern 0.16. could be cool to tag the releases on github to ease switching to a specific release.

**Comment by MichaelXavier** [comment]
Tagging is kind of dubious when there's multiple versioned packages on the repo. I recommend just using the git revision.
