### ISSUE TITLE
Katip + Aeson 2.0.0.0 Incompatibility

### ISSUE THREAD

**Issue by tbidne** [Soostone/katip#128]
Hello,

[Aeson-2.0.0.0](https://hackage.haskell.org/package/aeson-2.0.0.0) merged haskell/aeson/pull/866, which changed the type of its `Object` (see [here](https://github.com/haskell/aeson/pull/866/files#diff-9348de46ef4815e7364e37427909837240b95756c293e1fc0641944522c3f01bL354)). Unfortunately this is a breaking change:

```sh
Building library for katip-0.8.5.0..
[1 of 5] Compiling Katip.Core       ( src/Katip/Core.hs, dist/build/Katip/Core.o, dist/build/Katip/Core.dyn_o )

src/Katip/Core.hs:491:52: error:
    • Couldn't match type ‘Text’ with ‘A.Key’
      Expected type: [(A.Key, AnyLogPayload)]
        Actual type: [(Text, AnyLogPayload)]
    • In the second argument of ‘map’, namely ‘as’
      In the second argument of ‘($)’, namely ‘map go as’
      In the expression: object $ map go as
    |
491 |     toJSON (SimpleLogPayload as) = object $ map go as
    |                                                    ^^

src/Katip/Core.hs:524:20: error:
    • Couldn't match type ‘HM.HashMap Text v0’
                     with ‘Data.Aeson.KeyMap.KeyMap A.Value’
      Expected type: A.Object
        Actual type: HM.HashMap Text v0
    • In the expression:
        HM.filterWithKey (\ k _ -> k `elem` ks) $ toObject a
      In a case alternative:
          SomeKeys ks -> HM.filterWithKey (\ k _ -> k `elem` ks) $ toObject a
      In the expression:
        case foldMap (flip payloadKeys a) [(V0) .. verb] of
          AllKeys -> toObject a
          SomeKeys ks -> HM.filterWithKey (\ k _ -> k `elem` ks) $ toObject a
    |
524 |     SomeKeys ks -> HM.filterWithKey (\ k _ -> k `FT.elem` ks) $ toObject a
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Katip/Core.hs:524:65: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap A.Value’
                     with ‘HM.HashMap Text v0’
      Expected type: HM.HashMap Text v0
        Actual type: A.Object
    • In the second argument of ‘($)’, namely ‘toObject a’
      In the expression:
        HM.filterWithKey (\ k _ -> k `elem` ks) $ toObject a
      In a case alternative:
          SomeKeys ks -> HM.filterWithKey (\ k _ -> k `elem` ks) $ toObject a
    |
524 |     SomeKeys ks -> HM.filterWithKey (\ k _ -> k `FT.elem` ks) $ toObject a
    |                                                                 ^^^^^^^^^^
```

Changing the version bound on hackage is probably the quickest fix. Otherwise you'd want to throw this in the cabal file:

```cabal
, aeson >=0.6 && <1.6
```

I'm happy to assist however I can. Thanks!

**Comment by tbidne** [comment]
Thanks for the quick response!

Sure, I can look into those tasks. If I understand correctly, what you would ideally like to see would be:
1. Each subpackage has its own stack.yaml
2. Support both `aeson` 1.x and 2.x via CPP where possible (I'm assuming your reference to pinning `aeson-2` was purely for testing purposes, not something you'd want committed).

Happily, I was just now able to get `katip` to build with `aeson-2` (also required manually upgrading to `semialign-1.2`) with trivial changes, so this plan seems viable.

**Comment by tbidne** [comment]
Oh! Of course, that makes perfect sense. I am usually a cabal/nix user, so I mistakenly believed the pinned `stack.yaml` would impact other users. Thank you for the clarification. I can draft a PR with the individual `stack.yaml`, CPP, and pinned deps for your review, if that works for you.

**Comment by MichaelXavier** [comment]
That'd be great. Thank you!

**Comment by phadej** [comment]
Looks like `katip-0.8.7.0` is `aeson-2` compatible. However other from 0.8 series weren't, so I made revisions.

I also noted that `katip-0.8`:
- isn't text-2 compatible, and needs lower bounds on
- text as well, for Lift Text instance
- stm >=2.4.4.1: isFullTBQueue (added in 2.4.3, but 2.4.4.1 allows base-4.9)
- async >=2.1.0: Control.Concurrent.Async module (and the lowest reachable version)
- resourcet >=1.2.0: No instance for (MonadBase IO m) arising from the 'deriving' clause of a data type declaration. (With GHC-8.0, later GHCs are smarter)

See https://hackage.haskell.org/package/katip-0.8.7.0/revisions/

Please incorporate these lower bounds so they are present in the next releases, thanks!

**Comment by MichaelXavier** [comment]
I've updated the lower bounds and supported GHC versions. Thank you!
