### ISSUE TITLE
Behavior of logMsg and quick reference documentation

### ISSUE THREAD

**Issue by mightybyte** [Soostone/katip#14]
I noticed that the logMsg function has different behavior than I expected.  logMsg seems to overwrite the last namespace item with whatever is supplied.  I would have expected it to add to the namespace list.  Is this intended?  If so, I think it would be nice to have a quick reference matrix of all the log functions and their behavior.

**Comment by MichaelXavier** [comment]
This is intended. Nothing that Katip provides actually appends to the namespace or item automatically. In practice we found the best way do to do this is to use the monoid instances of `Namespace` and `LogContexts` and to to write simple combinators to append to them. Katip is generic enough that we couldn't really provide this out of the box, but for stacks with a ReaderT foundation, its as simple as a `local` and a `mappend`. 

There actually isn't anything like an ambient context in `LogEnv` or `Katip`. This is what `KatipContext` is for, but I totally see what caused the confusion: `_logEnvNs` is actually used for the `app` field of the `LogItem` and should be renamed (or at least documented) as `_logEnvApp`. Also, I want to use your intuition about how namespaces work as a cue that the docs need to be more explicit.

So my plan is:
1. Explicitly talk about the semantics of namespacing and what you should do if you want appending behavior.
2. I'm not sure if the misleading name `_lsEnvNs` is actually work a breaking change (though I'd be surprised if anyone touches that directly), but we have other beaking changes lined up so maybe its worth just renaming and documenting that field.

**Comment by mightybyte** [comment]
I don't have a strong opinion either way as to whether you change the behavior to match my intuition or change the documentation to avoid people getting that intuition in the first place.  I think I got that idea because of the [KatipContext type class](http://hackage.haskell.org/package/katip-0.1.1.0/docs/Katip.html#t:KatipContext).

The `logFM` and `logItemM` functions both have a KatipContext constraint.  And your example also includes a [KatipContext instance](https://github.com/Soostone/katip/blob/master/katip/examples/example.hs#L87).  So I think these things just made me assume that KatipContext was the fully supported default.  Now that I look more closely I see that `logF`, `logMsg`, and `logT` do not have the KatipContext constraint.  So I guess it is possible to infer the information.

I think that at the very least the distinction between the log functions that have a KatipContext constraint and those that don't should be made much more clear in the documentation.  Possibly by having two separate sections.  Alternatively you could make all the exported logging functions uniformly use KatipContext everywhere.

**Comment by MichaelXavier** [comment]
@mightybyte If you don't mind, could you take a look at [this diff](https://github.com/Soostone/katip/commit/2163df6e727e7a63faa3b03f69650d9b666f3dd2) and let me know what you think? Chanages are:

1. More clarity around the app field in LogEnv.
2. I've segregated log functions for Katip and KatipContext into their own sections. I've added a header and examples at the top of each section explaining the use case for either.
3. Your intuition was correct and I tried to emphasize that KatipContext is the right choice most of the time. Usually your intent is to accumulate context. The lower level functions are there for cases where you need precise control over logcontext. KatipContext's functions are actually implemented in terms of these lower level functions.
4. Added helpers for adding namespace and context to `KatipContextT`, which is our prefab monad transformer if you don't have your own. I think between this and the example code, it should be easy for folks with their own stacks and using `KatipContextT` to work with katip's contextual logging features.

I think this will probably be the last of the features before our next breaking release.

**Comment by mightybyte** [comment]
Looks good!
