### ISSUE TITLE
How do you create instances of KatipContext when you don't have access to the other monad constructor?

### ISSUE THREAD

**Issue by tonicebrian** [Soostone/katip#147]
I'm using [Control.Concurrent.Actor](https://hackage.haskell.org/package/stm-actor-0.3.1.0/docs/Control-Concurrent-Actor.html) for a concurrent code I'm doing. The internal monad `m` is where I have my domain logic maybe even doing some IO. I'd loke to log when a message is received in the actor using Katip and for that I wanted to create instances of : 

```haskell
instance KatipContext m => ActionT message m where 
   getKatipContext = lift getKatipContext  --- Compile!!
   localKatipContext f (ActionT message m) --- Doesn't compile because there is no `ActionT` constructor in this monad.
```

How do you follow the recipe for adding KatipContext to a monad where I haven't the constructor? (In my case monad `ActionT message m a`

**Comment by MichaelXavier** [comment]
The instance you're writing might be a bit too broad and would be orphaned. The typeclass methods for `KatipContext` were designed to be like `ask` and `local` in `Reader`-like monads. If your actual monad `m` is a `MonadReader r` where `r` contains your katip contexts and soforth, you can utilize `ActionT`'s `MonadReader` instance:

```haskell
{-# LANGUAGE DerivingStrategies #-}

module Main where

import Control.Concurrent.Actor
import Control.Monad.Reader
import Katip

data MyReaderState = MyReaderState
  { myReaderState_logContexts :: LogContexts
  }

newtype MyMonad m a = MyMonad (ReaderT MyReaderState m a)
  deriving newtype (Functor, Applicative, Monad, MonadReader MyReaderState)

instance (Monad m) => KatipContext (ActionT message (MyMonad m)) where
  getKatipContext = asks myReaderState_logContexts
  -- This is a bit cleaner with lenses
  localKatipContext modifyLogContexts = local (\myState -> myState { myReaderState_logContexts = modifyLogContexts (myReaderState_logContexts myState) })

```
Will that work?

**Comment by tonicebrian** [comment]
Yep I forgot about the fact of  the provided instances `MonadReader r m => MonadReader r (ActionT message m)`. Then as you pointed, by partial function application I can avoid having to state the ActionT constructor. The only think is that yes, it is an orphan instance but it is ok in my application, I just added `{-# OPTIONS_GHC -fno-warn-orphans #-}` at the top of the file and that was it. The final file looks like:

```haskell
{-# OPTIONS_GHC -fno-warn-orphans #-}

module Adapters.Actors.Logging where

import Control.Concurrent.Actor
import Control.Lens
import Control.Monad.Reader.Class
import Katip
import Logging
import UseCases.Interactions.InteractionM
import Prelude

instance Katip (ActionT message InteractionM) where
  getLogEnv = view (katipEnv . logEnv)
  localLogEnv f = local (over (katipEnv . logEnv) f)

instance KatipContext (ActionT message InteractionM) where
  getKatipContext = view (katipEnv . kLogContext)
  localKatipContext f = local (over (katipEnv . kLogContext) f)
  getKatipNamespace = view (katipEnv . kNamespace)
  localKatipNamespace f = local (over (katipEnv . kNamespace) f)
```

Thanks!!

**Comment by MichaelXavier** [comment]
You're welcome! Looks great!
