### ISSUE TITLE
Something funky with the katip-elasticsearch docs on hackage

### ISSUE THREAD

**Issue by mightybyte** [Soostone/katip#15]
When I go to the hackage docs for katip-elasticsearch-0.1.1.0 I actually get docs for 0.1.0.0.  The comment for defaultEsScribeCfg says it defaults to NoIndexSharding, but when I `cabal get` the package, the code and comment says DailyIndexSharding.  It also says 0.1.0.0 in the upper left corner of the page.  Not sure how it got into this bizarre situation, but it was confusing until I figured out what was going on.

**Comment by MichaelXavier** [comment]
Good catch. I'm not sure what happened. I've given up hope on hackage ever building docs, so I've been using the `neil` package to upload docs. I've just run that and it looks like the docs that it uploads have the correct info now, but [this page](https://hackage.haskell.org/package/katip-elasticsearch-0.1.1.0/docs/Katip-Scribes-ElasticSearch.html) still hasn't updated so I'm not sure what is going on. Any ideas?

**Comment by mightybyte** [comment]
Hmmm, I have no idea.

**Comment by MichaelXavier** [comment]
Looks like that page finally updated, so there was some sort of cache or other process at play.
