### ISSUE TITLE
Deeply render logitem keys in Handle scribe

### ISSUE THREAD

**Issue by mkscrg** [Soostone/katip#16]
I was surprised by `mkHandleScribe`s [shallow rendering](https://github.com/Soostone/katip/blob/425a54dfc5183ae2258c85ba7490484d58b9df53/katip/src/Katip/Scribes/Handle.hs#L31) of `LogItem` keys.

E.g. this program

```haskell
{-# LANGUAGE OverloadedStrings, TemplateHaskell #-}
module Main where

import Data.Aeson
import Katip
import System.IO

main :: IO ()
main = do
    stdoutScribe <- mkHandleScribe (ColorLog False) stdout DebugS V3
    logEnv <- registerScribe "stdout" stdoutScribe <$> initLogEnv "test" "test"
    runKatipT logEnv $ do
        $logT (sl "foo" ["bar" .= ("baz"::String)]) "test" InfoS "log message"
```

outputs

```text
[2016-03-27 23:29:34][test.test][Info][core-01][202][ThreadId 106][foo:][main:Main KatipIssue.hs:14:9] log message
                                                                  ^^^^^^ no nested data :(
```

Is this behavior missing from the docs, or am I missing something fundamental about `katip`?

**Comment by MichaelXavier** [comment]
I can't think of a strong reason to not allow deep rendering. It is worth noting that the `LogItem` typeclass' `payloadKeys` function only selects toplevel keys from an object, so as long as a toplevel key makes it through, we should probably render any lower level keys.

@ozataman any reason not to render subkeys? I think in the example above you'd expect to see `[foo.bar:baz]`.
