### ISSUE TITLE
Switch from regex-tdfa-rc to regex-tdfa

### ISSUE THREAD

**Issue by neongreen** [Soostone/katip#20]
I'm the new maintainer of regex-tdfa and I intend to keep it perpetually buildable, so there's no reason to depend on regex-tdfa-rc anymore (unless there is some reason that I don't see, right).

If the `Show (a -> b)` instance is the reason you're using regex-tdfa-rc, then starting from `1.2.2` regex-tdfa doesn't export that instance anymore.

**Comment by MichaelXavier** [comment]
Looking over the logs I'm not sure why I ended up using regex-tdfa-rc in particular and it builds and tests pass with your version so I've switched. Thanks.
