### ISSUE TITLE
Add convenience newtypes for logging JSON

### ISSUE THREAD

**Issue by mightybyte** [Soostone/katip#21]
I have found something like the following useful in my use of Katip.

    newtype LogAllFields = LogAllFields { unLogAllFields :: Value }
    instance ToJSON LogAllFields where
        toJSON = unLogAllFields
    instance ToObject LogAllFields where
    instance LogItem LogAllFields where
        payloadKeys _ _ = AllKeys

Perhaps this (or something similar, perhaps with control over the verbosity) should be added to Katip?

**Comment by MichaelXavier** [comment]
Hmm, have you looked at `SimpleLogPayload` and `sl`. I didn't add these and I've not used them so I'm not sure how the ergonomics compare but it seems pretty close to what you're talking about. The underlying specification:

```haskell
newtype SimpleLogPayload = SimpleLogPayload {
      unSimpleLogPayload :: [(Text, AnyLogPayload)]
    }

-------------------------------------------------------------------------------
-- | A built-in convenience log payload that won't log anything on 'V0',
-- but will log everything in any other level of verbosity. Intended
-- for easy in-line usage without having to define new log types.
--
-- Construct using 'sl' and combine multiple tuples using '<>' from
-- 'Monoid'.
instance ToJSON SimpleLogPayload where
    toJSON (SimpleLogPayload as) = object $ map go as
      where go (k, AnyLogPayload v) = k A..= v

instance ToObject SimpleLogPayload

instance LogItem SimpleLogPayload where
    payloadKeys V0 _ = SomeKeys []
    payloadKeys _ _ = AllKeys

instance Monoid SimpleLogPayload where
    mempty = SimpleLogPayload []
    SimpleLogPayload a `mappend` SimpleLogPayload b = SimpleLogPayload (a `mappend` b)


-------------------------------------------------------------------------------
-- | Construct a simple log from any JSON item.
sl :: ToJSON a => Text -> a -> SimpleLogPayload
sl a b = SimpleLogPayload [(a, AnyLogPayload b)]
```

So, the differences of note are that:
1. It by default takes the structure of an Object rather than a Value, which is kind of a requirement anyways.
2. It follows the convention that V0 should log nothing but otherwise logs everything.
3. It is meant to be used from the `sl` constructor and monoid, so an ad hoc payload object may look like `sl "foo" 42 <> sl "bar" True` or maybe with `mconcat` if you have a lot of keys. On my first impression, the ergonomics seem pretty nice.

Thoughts?

**Comment by mightybyte** [comment]
Yes, I did try `sl`.  But it wasn't giving me the desired effect, possibly because of issue #22.  I didn't realize 0.2 was out.  I'll give that a try and report back.

**Comment by mightybyte** [comment]
Yes, 0.2 does fix this and `sl` works nicely.  One thing I did notice is that the handle scribe and the elasticsearch scribe give slightly different log records.  With the handle scribe, if I do `sl "foo" foo <> sl "bar" bar`, I get keys with a prefix of `foo.` and `bar.`.  But with the elasticsearch scribe I get prefixes of `data.foo.` and `data.bar.`.  I don't know if you care about this or not, but it seems like it would be nice for them to be the same.  Maybe we should open a different issue for that?

**Comment by MichaelXavier** [comment]
Glad that worked!

So the "data" key in elasticsearch is to help prevent conflicts between userland log item keys and the pretty much fixed set of keys we send to elasticsearch, so if there was ever a conflict between them, I'd keep data. The handle scribe including `data.` I guess could be useful if you were using it as a way to better grep log files. I don't feel too strongly either way on it, as the ES integration was specifically to avoid having to try to reliably parse log files.

**Comment by mightybyte** [comment]
I don't feel strongly about it.  I just thought I'd point it out in case you cared.  Adding the `data.` prefix on the handle scribe is perfectly fine with me.
