### ISSUE TITLE
How is JSON supposed to be logged?

### ISSUE THREAD

**Issue by mightybyte** [Soostone/katip#22]
This comment in the example made me think that JSON structures being logged as context would be completely flattened so that all data inside the structure would be visible in the log.

https://github.com/Soostone/katip/blob/master/katip/examples/example_lens.hs#L58

But that does not seem to be the case.  If I log an Object `object ["foo" .= obj]`, where `obj` is some other JSON Value with a complex structure, none of the data appears in my logs.  I only see `[foo:]`.  Is the comment in the example incorrect and you don't want to flatten the structure and include everything now?

I feel it would be very useful to have something that would flatten a whole JSON structure and not throw anything out.  But I also recognize that this might not be the right thing to do.  So perhaps we could have some newtype wrappers that would provide multiple possibilities.  I can envision at least three that seem useful: one for logging the full structure, one for logging only the the top level of the tree, and one for logging only primitives (which seems to be the current behavior).

**Comment by MichaelXavier** [comment]
Have you tried out version 0.2.0.0? The Handle Scribe in the initial release actually just discarded nested object keys. I think this snuck by us and there was no specific intent there. I resolved #16 and released it under 0.2.0.0. Note that this issue only extended to the Handle Scribe, and if you're still experiencing it dropping nested objects in the output, that's a bug.

**Comment by mightybyte** [comment]
It looks like 0.2 fixes everything, thanks!
