### ISSUE TITLE
monad-control is proliferating

### ISSUE THREAD

**Issue by bitemyapp** [Soostone/katip#25]
Adding a MonadBaseControl instance to the examples would help.

Example of where it can arise:

```
    No instance for (MonadBaseControl IO (Logging IO))
      arising from a use of ‘withPostgresqlPool’
```

We use Persistent and Esqueleto at work because we don't really have anything else which both:

1. Reifies the transactions into a monad that can be combined/smushed (postgresql-transactional closed the gap for the `-simple` family but I haven't tested it rigorously)

2. Type-safe queries. Esqueleto is quite imperfect here, not being total and having obnoxious overlaps with Aeson and lens for the operators, but opaleye takes too much boilerplate atm.

**Comment by bitemyapp** [comment]
Here's a more complete example that doesn't solve the incompatibility with `MonadLogger`, but which does solve the, "but I have to change all my invocations of the logger now", problem.

```haskell
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE UndecidableInstances #-}

module Betterteam.Logging where

import Betterteam.Import hiding ((<>))
import Control.Monad.Base
import Control.Monad.Reader
import Control.Monad.Trans.Control
import Data.Monoid ((<>))
import Katip
import Katip.Core
import Language.Haskell.TH


data LogState = LogState {
    lsNamespace :: Namespace
  , lsContext   :: LogContexts
  , lsLogEnv    :: LogEnv
  }

newtype LoggingT m a = LoggingT {
      unLoggingT :: ReaderT LogState m a
    } deriving (MonadReader LogState, Functor, Applicative, Monad, MonadIO, MonadTrans)

instance MonadBase b m => MonadBase b (LoggingT m) where
  liftBase = liftBaseDefault

instance MonadTransControl LoggingT where
  type StT LoggingT a = StT (ReaderT Int) a
  liftWith = defaultLiftWith LoggingT unLoggingT
  restoreT = defaultRestoreT LoggingT

instance MonadBaseControl b m => MonadBaseControl b (LoggingT m) where
  type StM (LoggingT m) a = ComposeSt LoggingT m a
  liftBaseWith = defaultLiftBaseWith
  restoreM = defaultRestoreM

instance (MonadIO m) => Katip (LoggingT m) where
  getLogEnv = asks lsLogEnv

instance (MonadIO m) => KatipContext (LoggingT m) where
  getKatipContext = asks lsContext
  getKatipNamespace = asks lsNamespace

-- | Merge some context into the log only for the given block
addContext :: (LogItem i, MonadReader LogState m) => i -> m a -> m a
addContext i = local (\r -> r { lsContext = lsContext r <> ctxs })
  where ctxs = liftPayload i

-- | Add a layer of namespace to the logs only for the given block
addNamespace :: (MonadReader LogState m) => Namespace -> m a -> m a
addNamespace ns = local (\r -> r { lsNamespace = lsNamespace r <> ns })

runLoggingT :: LogState -> LoggingT m a -> m a
runLoggingT s f = runReaderT (unLoggingT f) s

logItemMShow
    :: (Applicative m, KatipContext m, Katip m, Show msg)
    => Maybe Loc
    -> Severity
    -> msg
    -> m ()
logItemMShow loc sev msg = do
    ctx <- getKatipContext
    ns <- getKatipNamespace
    logItem ctx ns loc sev (logStr (tshow msg))

logDebugSH :: ExpQ
logDebugSH =
  [| logItemMShow (Just $(getLocTH)) DebugS |]

logInfoSH :: ExpQ
logInfoSH =
  [| logItemMShow (Just $(getLocTH)) InfoS |]

logWarnSH :: ExpQ
logWarnSH =
  [| logItemMShow (Just $(getLocTH)) WarningS |]

logErrorSH :: ExpQ
logErrorSH =
  [| logItemMShow (Just $(getLocTH)) ErrorS |]
```

**Comment by MichaelXavier** [comment]
I'm a bit confused about what this example is providing. I could add the transcontrol/basecontrol instances to the example, I like that because they're consistently the weirdest to implement (and are already implemented in the KatipT/KatipContextT reference transformers). Count me in on that.

The rest seems to focus on showable messages. Do you know about `showLS :: Show a => a -> LogStr` that seems like it would obviate the need for all of these log variations you've got?

**Comment by bitemyapp** [comment]
@MichaelXavier ignore the showable bits. Just being Gonzo and sharing the whole module.

Mostly shared for the transcontrol/basecontrol/monadtrans etc. because anyone using Yesod/Persistent will run into needing those instances. Pretty sure Snap 1.0 users will too. Can't speak to what Happstack et al. are doing.
