### ISSUE TITLE
Why ToObject requires ToJSON?

### ISSUE THREAD

**Issue by sopvop** [Soostone/katip#33]
If it is only to provide default instance, then I think it would be better to
use default signatures, and for ancient GHCs provide something like `defaultToObject`

This changes should not break API, I think.

```.haskell

defaultToObject :: a -> A.Object
defaultToObject v = case toJSON v of
      A.Object o -> o
      _        -> mempty

class ToObject a where
    toObject :: a -> A.Object
    default toObject :: ToJSON a => a -> A.Object
    toObject = defaultToObject

```

**Comment by MichaelXavier** [comment]
@ozataman Not sure why we didn't go this route. I'm pretty sure any GHC versions we officially support would allow for this. Any objection? I'm pretty sure we did it this way specifically for the default instance.

**Comment by sopvop** [comment]
Oh, but this should require major bump, since maybe someone can use ToObject to also mean ToJSON constraint

**Comment by MichaelXavier** [comment]
@sopvop Ah ok, so to put it another way, if someone depended on `ToObject` and its superclass `ToJSON`, they'd lose the superclass and now in functions that need both, it would no longer be sufficient to specify only `ToObject a`, they'd have to specify `ToJSON a, ToObject a`. In that case we would want that version bump, but the impact seems benign enough that we shouldn't worry about this change being too disruptive.
