### ISSUE TITLE
Handle scribe interleaves concurrent logs

### ISSUE THREAD

**Issue by MichaelXavier** [Soostone/katip#34]
If you have concurrent logs going to a handle scribe, they get interleaved in the file. I'm not sure if we can get away with setting the handle buffering to line buffering or if we'll need to set up a write queue like we have in `katip-elasticsearch` to linearize the logs.

**Comment by sopvop** [comment]
I think the buffered logs would be much more better in general.

**Comment by MichaelXavier** [comment]
@sopvop both solutions are a form of buffering. Which are you referring to? :)

**Comment by sopvop** [comment]
I refer to buffering outside of Handle, with a queue :)

**Comment by MichaelXavier** [comment]
@sopvop I did some benchmarking (not included in commit) and was pretty happy with the simplest thing I could think of, just an mvar lock. As you can expect, this has minimal overhead that scales up as more concurrent writes are added. Do you think this is good enough for a v1 effort? I didn't want to get into managing a worker thread with channels if a simple mvar would do.

**Comment by MichaelXavier** [comment]
Time's up. Merged.
