### ISSUE TITLE
Support Aeson 1.0

### ISSUE THREAD

**Issue by folsen** [Soostone/katip#38]
I am currently using Katip, but I also want to use some of the newer features of Aeson 1.0, so I'd love to see support for Aeson 1.0.

**Comment by mightybyte** [comment]
I second this.  The latest version of aeson has a more comprehensive set of FromJSON/ToJSON instances, which are very useful.

**Comment by MichaelXavier** [comment]
Merged the releated PR. I'll try to get a release out today!

**Comment by MichaelXavier** [comment]
Released in 0.3.1.0.
