### ISSUE TITLE
In multithread environment, `logMsg` appends '\n' in not a thread-safe way.

### ISSUE THREAD

**Issue by Heimdell** [Soostone/katip#40]
So, I get messages like:
```
[foo]bar1[foo]bar2[foo]bar3


[foo]bar4
[foo]bar5
```

Maybe, its from usage of `putStrLn`?

What can I do to negate this problem?

**Comment by MichaelXavier** [comment]
What version are you using? This was addressed in 0.3.0.0 in issue #34. I added an MVar around writes [here](https://github.com/Soostone/katip/blob/master/katip/src/Katip/Scribes/Handle.hs#L68). If its still doing this, its a bug.

**Comment by Heimdell** [comment]
It appears working right now, after I updated to `0.3.1.0`.
