### ISSUE TITLE
Handle Scribe Number formatting

### ISSUE THREAD

**Issue by BartAdv** [Soostone/katip#63]
Hello,

Currently, formatting uses default `Show` instance for Aeson Number (which is `Scientific`). This means, it renders integers with decimal places, like `24.0`. It's easy to fix (I have it on my branch), by using `isFloating` predicates from `scientific`, but the problem is that it detects `0.0` as integer (found it out by running Katip test suite).

Are you open for such change, or would you rather stay with current state?

At least in my case, the rationale is that, when it comes to numbers, I mostly log some kind of PKs and other identifiers, and it look really weird with decimal places :)

**Comment by MichaelXavier** [comment]
Yeah that sounds like a good solution. You may even try something like `either show show . floatingOrInteger` which hints reasonable types for either case, say `Double` and `Integer`.

**Comment by BartAdv** [comment]
Resolved by https://github.com/Soostone/katip/pull/64
