### ISSUE TITLE
`Eq`, `Show` instances for ScribeSettings

### ISSUE THREAD

**Issue by NicolasT** [Soostone/katip#69]
Any chance `ScribeSettings` could get `Eq`, `Show` and maybe some other instances? This would be useful for writing testcases for a library I'm working on, as well as being able to derive `Eq`, `Show` and whatnot for records including a `ScribeSettings` field.

**Comment by NicolasT** [comment]
Same goes for `ColorStrategy`, and potentially some other datatypes in the library.

**Comment by MichaelXavier** [comment]
I'd take a PR for the instances that you think are appropriately shown and Eq'd. Do note however its usually fine to just write orphaned instances for things you need for test (you pretty much always do this for Arbitrary if you're using QuickCheck).

**Comment by NicolasT** [comment]
FWIW, the ability to `Show` such records isn't only for testing purposes :) So orphans would be suboptimal.
