### ISSUE TITLE
Katip fails to log the location with logLocM

### ISSUE THREAD

**Issue by jkachmar** [Soostone/katip#77]
Apologies in advance for not extracting out a complete repro yet, I'm hoping this is something simple I'm overlooking.

Right now I've got this code in my application...
```haskell
  case auth of
    authErr -> do
      logDebugM [logt|User failed to authenticate: #{authErr}|]
    ...
```
...where `logDebugM = logLocM DebugS`, and `logt` is just a small wrapper around `Data.String.Interpolate` that calls `logStr` after the interpolation.

When I hit that code path, Katip outputs the following:
```
[2017-12-05 17:33:10][GetSensorId][Debug][vulkan-021182.local][2823][ThreadId 24][katip-0.5.1.0-ItoCb2QT4Y8K3hRJ7ruLFI:Katip.Monadic src/Katip/Monadic.hs:293:20] User failed to authenticate: Indefinite
```
...where it looks like it's picking up the `logLocM` line location _in_ the Katip module rather than the location that I'm calling from.

I've tried the above with normal Katip functions (e.g. `logLocM DebugS "Hello!"`) to similar effect.

The whole thing's running in a newtype for my application's transformer stack with the appropriate `Katip` and `KatipContext` instances (pretty much lifted from this repo's examples), which seems like it should be pretty standard.

**Comment by MichaelXavier** [comment]
Does it continue to report the wrong line number if you expand your functions completely for some given log line?

**Comment by jkachmar** [comment]
Not 100% sure what you mean by expanding my functions completely, but if I use `logLoc` and supply a dummy payload like this (in the same module):
```haskell
      let payload = SimpleLogPayload [("foo", AnyLogPayload $ object ["bar" .= ("baz" :: Text)])]
      logLoc payload mempty InfoS "Hello"
```
I get the following, with the correct location as-expected:
```
[2017-12-05 19:42:59][][Info][vulkan-021182.local][4269][ThreadId 728][foo.bar:baz][main:Harbinger.Handler.WorkplaceOccupancy.GetSensorId /Users/usr/src/myProj/library/MyProj/Handler/GetId.hs:55:7] Hello
```

**Comment by jkachmar** [comment]
So I simplified some of the above to:
```haskell
data AppEnv
  = AppEnv
  { _aeMetrics   :: !Metrics
  , _aeConnPool  :: !ConnectionPool
  , _aeContexts  :: !LogContexts
  , _aeNamespace :: !Namespace
  , _aeLogEnv    :: !LogEnv
  }

makeLenses ''AppEnv
```
And now my instances are effectively identical to what's provided in the example and I'm still getting the error.

**Comment by jkachmar** [comment]
For what it's worth, I've resolved this issue now by ditching `logLocM` entirely and switching to `logTM`.

**Comment by ozataman** [comment]
I wonder if there’s a version of log we can add that taps into GHC’s recently added stack trace system. Or do we already have that now?

**Comment by domenkozar** [comment]
Fix in https://github.com/Soostone/katip/pull/100
