### ISSUE TITLE
How to work with wai?

### ISSUE THREAD

**Issue by joneshf** [Soostone/katip#80]
I've got a `wai` application and I'd like to use `katip` for logging. What's a good way to add `Request` data to logs?

Is there a way to create a wai `Middleware` that would add `Request` data to a `LogContexts`?
 I've tried to figure this out for a bit, but can't seem to find anything that would work. Am I missing something?

If not a `Middleware`, what are my other choices? It seems like the only option is to add information to each route individually. Is that right?

**Comment by MichaelXavier** [comment]
I'd eventually like to start writing these example guides into the project to give sort of a cookbook to get various types of projects off the ground with Katip.

In your WAI application, what do you use for application configuration/state? Are you wrapping the wai stack with a Reader of some sort or are you just operating directly on IO and WAI?

**Comment by joneshf** [comment]
A cookbook would be great!

Yeah, it's a reader for the app:

```Haskell
data Env = Env LogEnv Namespace LogContexts
newtype App a = App (ReaderT Env IO a)
```

It's servant dealie, so maybe more complicated since getting the request is kind of hard.

**Comment by joneshf** [comment]
> various types of projects off the ground with Katip.

To be clear, I think the documentation is great as is now. I was able to get setup with stdout logging without getting lost.

**Comment by MichaelXavier** [comment]
I've definitely set up Katip on a few Servant apps now.

One challenge I think you'll face is, if I'm not mistaken, you at some point convert your servant app into a WAI app and run it through warp. In other words, I think your monad transformer for your app is *inside* WAI, so I don't think you would have access to your `Env` at the WAI middleware layer. Servant gives you an escape hatch to drop down to the WAI layer but that obviously destroys all the type-level benefits of using servant.

I'd probably advocate this, though I don't know if its best practice: write a [combinator](https://haskell-servant.readthedocs.io/en/stable/tutorial/ApiType.html#combinators) that at the type level injects the whole request. I think the closest one they have is `ReqBody`, though its isn't that close and is probably more complicated than what you'd add. I'm also kind of surprised this isn't a standard combinator, so it may be worth asking the servant folks if this is something they'd add or even if it is a terrible idea.

So you'd update your API's type to inject the `Request` at the root of your API's type, eg `Req :> TheRestOfYourAPI`, and then the root of your server will now take an additional parameter with the `Request`, which you'd pluck out fields and use `katipAddContext` and probably `sl` to add your context. Man, this sounds gnarley.

Alternatively, you could possibly use the `Vault` from wai or the `Context` primitive in servant. I think this is probably a general question you should ask the servant folks: how do you get the raw wai request and thread it through to the part where you run your custom transformer stack via `enter`?

**Comment by joneshf** [comment]
Great. Thanks for the direction!

**Comment by joneshf** [comment]
I feel really dumb...

`Application` is a type synonym. It's

```Haskell
type Application = Request -> (Response -> IO ResponseReceived) -> IO ResponseReceived
```

So if you have:

```Haskell
data Env = ...

type App a = ReaderT Env IO a

app :: Env -> Application
app env = serve (enter (NT liftApp) server)
    where
    liftApp :: App a -> Handler a
    liftApp = liftIO . flip runReaderT env
```

The way you get access to the request is by eta-expanding the function.

```Haskell
data Env = ...

type App a = ReaderT Env IO a

app :: Env -> Application
app env req = serve (enter (NT liftApp) server) req
    where
    liftApp :: App a -> Handler a
    liftApp = liftIO . flip runReaderT env . katipAddContext (sl "isSecure" $ isSecure req)
```

Talk about a brain fart! That's like Haskell 101.

Sorry for the noise 😊.

**Comment by MichaelXavier** [comment]
Wow! That ended up much simpler than I thought. My brain immediately went to typespace orbit, I didn't consider it would be that simple. I'll keep this one in my back pocket as I'm pretty sure request path/method logging context would be quite useful in my servant apps.
