### ISSUE TITLE
Add 'MonadReader' instance for 'NoLoggingT'

### ISSUE THREAD

**Issue by ChShersh** [Soostone/katip#90]
It would be great to add instance like this:

```haskell
instance MonadReader r m => MonadReader r (NoLoggingT m)
```

For now I don't see any reason why this instance shouldn't exist.

**Comment by MichaelXavier** [comment]
Updated in master. Will cut a release on a successful CI run.

**Comment by ChShersh** [comment]
@MichaelXavier Thanks a lot!
