### ISSUE TITLE
Easiest way to log JSON to the console?

### ISSUE THREAD

**Issue by tmbull** [Soostone/katip#95]
Hello, first I would like to say thanks for creating this library!

We were able to fairly easily add katip to our existing application, and are now logging to `stderr` using the built-in handle-based scribe. What I would like to know is if it is possible to log directly to the console as JSON rather than logging using the traditional "bracket" format? It seems to me that we will need to create a custom `Scribe` to to this, but I just wanted to make sure I wasn't missing anything.

**Comment by MichaelXavier** [comment]
You would need to create a custom scribe right now. Handle scribe is still really basic and I'm not super happy about it. One improvement that I think would unlock a lot of customization is if we exported a version of `mkHandleScribe` that allowed you to specify your own [formatItem](https://hackage.haskell.org/package/katip-0.6.0.0/docs/Katip-Scribes-Handle.html#v:formatItem) `:: LogItem a => Bool -> Verbosity -> Item a -> Builder`. From there, it'd be easy to tack on combinators that added or removed information form the standard formatter, output to JSON or some other file format. Do you think you'd be up for forking, trying out that functionality locally to see if it works for your use case and possibly submitting a PR? I could add this functionality myself but I'd much rather there be a motivating use case that could prove out this feature like you have presented.

**Comment by tmbull** [comment]
Sure, I ended up writing my own version of `mkHandleScribe` that writes the logItem out as JSON. However, I like your approach better and would be happy to contribute. Expect a PR in the next day or so.

**Comment by tmbull** [comment]
So much for a day or so... My apologies for not getting to this sooner. I had a workaround in place so it slipped down my list of priorities. In any case, I took a look at this today, but didn't get very far unfortunately. See my progress [here](https://github.com/tmbull/katip/commit/fe76d57f878aac4862284af2c3427af61c6995bd). 

```
src\Katip\Scribes\Handle.hs:68:18: error:
        * Ambiguous type variable `a0' arising from a use of `mkHandleScribeWithFormatter'
          prevents the constraint `(LogItem a0)' from being solved.
          Probable fix: use a type annotation to specify what `a0' should be.
          These potential instances exist:
            instance LogItem SimpleLogPayload -- Defined in `Katip.Core'
            instance LogItem () -- Defined in `Katip.Core'
        * In the expression: mkHandleScribeWithFormatter formatItem
          In an equation for `mkHandleScribe':
              mkHandleScribe = mkHandleScribeWithFormatter formatItem
       |
    68 | mkHandleScribe = mkHandleScribeWithFormatter formatItem
       |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    src\Katip\Scribes\Handle.hs:80:21: error:
        * Couldn't match type `a1' with `a'
          `a1' is a rigid type variable bound by
            a type expected by the context:
              forall a1. LogItem a1 => Item a1 -> IO ()
            at src\Katip\Scribes\Handle.hs:80:14-37
          `a' is a rigid type variable bound by
            the type signature for:
              mkHandleScribeWithFormatter :: forall a.
                                             LogItem a =>
                                             ItemFormatter a
                                             -> ColorStrategy
                                             -> Handle
                                             -> Severity
                                             -> Verbosity
                                             -> IO Scribe
            at src\Katip\Scribes\Handle.hs:70:1-124
          Expected type: Item a1 -> IO ()
            Actual type: Item a -> IO ()
        * In the first argument of `Scribe', namely `logger'
          In the second argument of `($)', namely `Scribe logger (hFlush h)'
          In a stmt of a 'do' block: return $ Scribe logger (hFlush h)
        * Relevant bindings include
            logger :: Item a -> IO ()
              (bound at src\Katip\Scribes\Handle.hs:77:9)
            formatItem' :: ItemFormatter a
              (bound at src\Katip\Scribes\Handle.hs:71:29)
            mkHandleScribeWithFormatter :: ItemFormatter a
                                           -> ColorStrategy
                                           -> Handle
                                           -> Severity
                                           -> Verbosity
                                           -> IO Scribe
              (bound at src\Katip\Scribes\Handle.hs:71:1)
       |
    80 |     return $ Scribe logger (hFlush h)
```

The issue seems to be the type variable in the `formatItem` function, and I'm not sure how to resolve the error in this case. Any advice? If I can get past this error, I would be happy to clean things up, add documentation, etc. and submit a PR.

**Comment by MichaelXavier** [comment]
@tmbull I'm probably butchering the terminology because I don't discuss this type of stuff often but I think you have to limit the scope of your type variable. I cloned your branch and changing the type signature of `mkHandleScribeWithFormatter` to `mkHandleScribeWithFormatter :: (forall a. LogItem a => ItemFormatter a) -> ColorStrategy -> Handle -> Severity -> Verbosity -> IO Scribe` fixed the compile error. The tests pass as well.

**Comment by tmbull** [comment]
@MichaelXavier Thanks! That makes sense. I had my suspicions yesterday that this had something to do with the scoping of the type variable. I had tried adding the explicit forall, but did scope it to the first parameter. 

I'll get this cleaned up, add a JSON formatter, and submit a PR.

**Comment by tmbull** [comment]
@MichaelXavier Sorry again for the slow response. I've submitted a PR (#97). Please let me know if there are any changes you would like for me to make, and I'll try to get back to you ASAP this time.
