### ISSUE TITLE
Katip doesn't work with STM-2.5.0.0

### ISSUE THREAD

**Issue by Shimuuar** [Soostone/katip#96]
Signature of `newTBQueue` was changed to `Natural → STM (TBQueue a)` from `Int → STM (TBQueue a)` in 2.4. Just wanted to let you know. 

Also could you amend version ranges on hackage?

**Comment by MichaelXavier** [comment]
Released, `katip-elasticsearch-0.5.1.0` and `katip-0.6.1.0`

**Comment by Shimuuar** [comment]
Thank you!
